version: '3.8'

services:
  databasepg:
    image: postgres
    restart: always
    ports:
      - "6000:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=carface
  api:
    image: imanzabag/carface_server
    container_name: api
    links:
      - databasepg
    ports:
      - "3000:8080"
      - "8080:8080"
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://databasepg:5432/carface
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=root
      - SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING.JPA.HIBERNATE.DDL-AUTO=create
      - JWT.SECRET=Carface_AppDist@2023
      - SPRING.THYMELEAF.PREFIX=classpath:/templates/
      - SPRING.THYMELEAF.SUFFIX=.html
      - spring.servlet.multipart.max-file-size=5MB
      - spring.servlet.multipart.max-request-size=50MB
      - admin.correo=carfaceadmin@admin.com
      - admin.clave=2023@Iot_CarFace
      - aws.access_key_id=AKIAXUUN5CKLUUNQFQLC
      - aws.secret_access_key=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
      - aws.s3.region=us-east-1
      - aws.s3.bucket=carfacestorage
    volumes:
      - .:/usr/src/app
    restart: unless-stopped